# Setup
title:        春风习语
tagline:      春风习语
baseurl:      ""
paginate:     1

# About/contact
author:
  name: cuiliyan
  email: ly444983@live.com
  url: mailto:ly444983@live.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown