# Setup
title:        春风习语理论学习小组
tagline:      恪守忠诚，血性担当  敢为人先，勇于创新

baseurl:      ""
paginate:     1
permalink: /:categories/:short_year/:month/:title:output_ext
# About/contact
author:
  name: cuiliyan
  email: ly444983@live.com
  url: mailto:ly444983@live.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown